import type { Metadata } from "next";
import InfoPageShell from "../InfoPageShell";

export const metadata: Metadata = { title: "Privacy | NAMO Jan Connect", description: "How NAMO Jan Connect collects, uses, protects, and retains citizen information." };

export default function PrivacyPage() {
  return <InfoPageShell eyebrow="PRIVACY, IN PLAIN LANGUAGE" title={<>Your information serves your <em>complaint.</em></>} intro="We collect only what is needed to route, investigate, update, and resolve public-service complaints. Public reporting uses anonymized, aggregate information.">
    <section className="privacy-summary reveal-on-view"><div><span>Last updated</span><b>11 August 2026</b></div><p>This notice explains the platform’s current data practices and should be read alongside any department-specific collection notice shown when you file.</p></section>
    <section className="info-section policy-layout reveal-on-view"><nav aria-label="Privacy policy sections"><a href="#collect">What we collect</a><a href="#use">How we use it</a><a href="#share">Who can access it</a><a href="#retain">Retention</a><a href="#rights">Your rights</a></nav><div className="policy-copy"><article id="collect"><p className="eyebrow">01</p><h2>What we collect</h2><p>Account details such as name, email, and optional phone number; complaint content; location supplied by you; evidence files; service activity; and feedback. Basic security logs help prevent abuse and protect accounts.</p></article><article id="use"><p className="eyebrow">02</p><h2>How we use it</h2><p>We use personal data to authenticate you, route complaints, contact you about status changes, help departments investigate, maintain an audit trail, measure service quality, and meet legal obligations.</p></article><article id="share"><p className="eyebrow">03</p><h2>Who can access it</h2><p>The assigned department and authorized administrators can access the information needed to act. Other citizens cannot see your personal details. Public dashboards contain anonymized totals and performance measures.</p></article><article id="retain"><p className="eyebrow">04</p><h2>Retention and security</h2><p>Complaint records are retained only for the operational, accountability, and legal period that applies. Evidence is stored separately from structured records. Access controls, encrypted transport, and audit history help protect the platform.</p></article><article id="rights"><p className="eyebrow">05</p><h2>Your choices and rights</h2><p>You may request access, correction, deletion where permitted, or information about how your data was handled. You can also withdraw optional consent without affecting processing already required to resolve a complaint.</p><a className="text-link" href="/contact">Submit a privacy request →</a></article></div></section>
  </InfoPageShell>;
}

