import type { Metadata } from "next";
import InfoPageShell from "../InfoPageShell";

export const metadata: Metadata = { title: "Accessibility | NAMO Jan Connect", description: "Our accessibility approach, supported features, and ways to request assistance." };

export default function AccessibilityPage() {
  return <InfoPageShell eyebrow="ACCESS FOR EVERY CITIZEN" title={<>Public service should work for <em>everyone.</em></>} intro="NAMO Jan Connect is designed around perceivable, operable, understandable, and robust experiences across devices and assistive technologies.">
    <section className="info-section reveal-on-view"><div className="info-section-heading"><p className="eyebrow">OUR COMMITMENT</p><h2>Designed toward WCAG 2.2 AA.</h2><p>Accessibility is treated as an ongoing product responsibility, not a one-time checklist.</p></div><div className="principle-grid"><article><span>01</span><h3>Keyboard friendly</h3><p>Interactive controls follow a logical order and remain usable without a mouse or touchscreen.</p></article><article><span>02</span><h3>Screen-reader ready</h3><p>Landmarks, labels, live states, and descriptive status text support assistive navigation.</p></article><article><span>03</span><h3>Readable contrast</h3><p>Light and dark themes maintain clear hierarchy, legible typography, and meaningful non-color cues.</p></article><article><span>04</span><h3>Motion with choice</h3><p>Animations automatically reduce when your device requests reduced motion.</p></article></div></section>
    <section className="info-band accessibility-band reveal-on-view"><div><p className="eyebrow">BUILT-IN CONTROLS</p><h2>Adapt the experience.</h2></div><ul className="check-list"><li><span>✓</span> Persistent light and dark color themes</li><li><span>✓</span> Clear focus indicators for keyboard users</li><li><span>✓</span> Responsive text and touch-friendly targets</li><li><span>✓</span> Status labels that do not rely on color alone</li><li><span>✓</span> Reduced-motion support across page transitions</li></ul></section>
    <section className="info-section two-column reveal-on-view"><div><p className="eyebrow">NEED AN ALTERNATIVE?</p><h2>We will help you complete the task.</h2><p>If any part of the platform creates a barrier, tell us what you were trying to do, the page involved, and the assistive technology or device you use.</p><a className="text-link" href="/contact">Contact accessibility support →</a></div><aside className="contact-card"><span>Accessibility support</span><a href="mailto:accessibility@namojanconnect.in">accessibility@namojanconnect.in</a><p>We aim to acknowledge accessibility reports within two working days.</p></aside></section>
  </InfoPageShell>;
}

